[metadata]
name = rfdom
version = 0.1.0
author = douxxtech
author_email = douxx@douxx.tech
description = Hardware random number generator using RTL-SDR radio frequency noise
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/douxxtech/rfdom
project_urls =
    Bug Tracker = https://github.com/douxxtech/rfdom/issues
    Documentation = https://github.com/douxxtech/rfdom
    Source Code = https://github.com/douxxtech/rfdom
license = GPLv3
license_files = LICENSE
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Topic :: Security :: Cryptography
    Topic :: System :: Hardware

[options]
packages = find:
python_requires = >=3.7
install_requires =
    numpy>=1.19.0

[options.packages.find]
exclude =
    examples*
    tests*